# Generated by Django 4.1.7 on 2023-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_header_rename_ism_order_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='fakt',
            old_name='desc',
            new_name='desc_ru',
        ),
        migrations.RenameField(
            model_name='fakt',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='desc',
            new_name='desc_ru',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='productfaq',
            old_name='desc',
            new_name='desc_ru',
        ),
        migrations.RenameField(
            model_name='productfaq',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakt',
            name='desc_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakt',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='desc_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfaq',
            name='desc_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfaq',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
