# Generated by Django 4.1.7 on 2023-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_ru_order_name_remove_order_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
            ],
        ),
    ]
